import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import { createProductCommerce, ProductError, type Principal } from '../backend/commerce';
import { provisionAccount } from '../backend/auth';
import { createProductServer } from '../backend/api';

// Each run owns one isolated schema; production tables are never reset.
test('PostgreSQL commerce: persistence, ownership, concurrent reservation and lifecycle',async () => {
  if (!process.env.TEST_DATABASE_URL) throw new Error('TEST_DATABASE_URL is required; this test must run against PostgreSQL');
  const root = new Pool({connectionString:process.env.TEST_DATABASE_URL});
  const schema='test_'+randomUUID().replaceAll('-','');
  await root.query(`CREATE SCHEMA "${schema}"`);
  const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,options:`-c search_path=${schema}`});
  const alice:Principal={id:'alice',role:'customer'};
  const bob:Principal={id:'bob',role:'customer'};
  const operator:Principal={id:'staff',role:'operator',storeIds:['pilot']};
  const payment:Principal={id:'verified-payment-provider',role:'payment'};
  const code=(expected:string)=>(failure:unknown)=>failure instanceof ProductError && failure.code===expected;
  const request={storeId:'pilot',fulfilment:'store' as const,lines:[{sku:'TEST-A',quantity:1}]};
  try {
    await pool.query(await readFile(new URL('../backend/schema.sql',import.meta.url),'utf8'));
    await pool.query("INSERT INTO stores VALUES('pilot','TEST STORE',true); INSERT INTO products VALUES('TEST-A','TEST PRODUCT',1299,500,true),('TEST-B','TEST PRODUCT B',299,100,true); INSERT INTO inventory VALUES('pilot','TEST-A',1,0),('pilot','TEST-B',1,0)");
    const service=createProductCommerce(pool);
    const qa=await service.quote(alice,request), qb=await service.quote(bob,request);
    const results=await Promise.allSettled([service.placeOrder(alice,qa.id,'alice-key-1'),service.placeOrder(bob,qb.id,'bob-key-001')]);
    assert.equal(results.filter(r=>r.status==='fulfilled').length,1,'only one customer can reserve last item');
    const winner=results.find(r=>r.status==='fulfilled')!;
    assert.equal(winner.status,'fulfilled');
    if(winner.status!=='fulfilled') throw new Error('No winner');
    const original=winner.value;
    const owner=original.customerId==='alice'?alice:bob;
    const other=owner===alice?bob:alice;
    const key=owner===alice?'alice-key-1':'bob-key-001';
    const restarted=createProductCommerce(pool);
    assert.equal((await restarted.getOrder(owner,original.id)).id,original.id,'survives module restart');
    assert.equal((await restarted.placeOrder(owner,original.quote.id,key)).id,original.id,'retry reuses order');
    await assert.rejects(restarted.getOrder(other,original.id),code('FORBIDDEN'));
    await assert.rejects(restarted.transition(operator,original.id,1,'paid'),code('FORBIDDEN'));
    await restarted.transition(owner,original.id,1,'cancelled');
    assert.equal((await pool.query("SELECT reserved FROM inventory WHERE sku='TEST-A'")).rows[0].reserved,0);
    const q=await restarted.quote(alice,request);
    const duplicate=await Promise.all(Array.from({length:8},()=>restarted.placeOrder(alice,q.id,'repeat-key')));
    assert.equal(new Set(duplicate.map(o=>o.id)).size,1);
    const o=duplicate[0];
    await restarted.transition(payment,o.id,1,'paid');
    await assert.rejects(restarted.transition(operator,o.id,1,'preparing'),code('VERSION_CONFLICT'));
    await restarted.transition(operator,o.id,2,'preparing');
    await assert.rejects(restarted.transition(operator,o.id,3,'shipped'),code('INVALID_TRANSITION'));
    await restarted.transition(operator,o.id,3,'ready_for_pickup');
    await restarted.transition(operator,o.id,4,'completed');
    const stock=(await pool.query("SELECT * FROM inventory WHERE sku='TEST-A'")).rows[0];
    assert.equal(stock.on_hand,0); assert.equal(stock.reserved,0);
    assert.equal((await pool.query('SELECT count(*)::int AS n FROM outbox')).rows[0].n,7);
    // A failed second line rolls back an already-reserved first line.
    await pool.query("UPDATE inventory SET on_hand=1 WHERE sku='TEST-A'");
    const multi=await restarted.quote(alice,{...request,lines:[{sku:'TEST-A',quantity:1},{sku:'TEST-B',quantity:1}]});
    await pool.query("UPDATE inventory SET on_hand=0 WHERE sku='TEST-B'");
    await assert.rejects(restarted.placeOrder(alice,multi.id,'rollback-key'),code('OUT_OF_STOCK'));
    assert.equal((await pool.query("SELECT reserved FROM inventory WHERE sku='TEST-A'")).rows[0].reserved,0);
    const home=await restarted.quote(alice,{...request,fulfilment:'home',postalCode:'52100'});
    const delivery=await restarted.placeOrder(alice,home.id,'home-key-001');
    await restarted.transition(payment,delivery.id,1,'paid');
    await restarted.transition(operator,delivery.id,2,'preparing');
    await restarted.transition(operator,delivery.id,3,'shipped');
    await restarted.transition(operator,delivery.id,4,'completed');
    assert.equal((await pool.query("SELECT on_hand FROM inventory WHERE sku='TEST-A'")).rows[0].on_hand,0);
    const accountId=await provisionAccount(pool,'customer@example.test','test-password-only','customer');
    await provisionAccount(pool,'operator@example.test','test-password-only','operator',['pilot']);
    const api=createProductServer(pool);
    await new Promise<void>(resolve=>api.listen(0,'127.0.0.1',resolve));
    const address=api.address();if(!address || typeof address==='string')throw new Error('Missing port');
    const base=`http://127.0.0.1:${address.port}`;
    const post=(path:string,value:unknown,token?:string)=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(value)});
    try {
      const page=await fetch(base+'/operations');assert.equal(page.status,200);
      assert.match(page.headers.get('content-security-policy')??'',/frame-ancestors 'none'/);
      assert.match(await page.text(),/Gestione ordini/);
      assert.equal((await fetch(base+'/v2/orders')).status,401);
      assert.equal((await post('/v2/auth/login',{email:'customer@example.test',password:'wrong'})).status,401);
      const response=await post('/v2/auth/login',{email:'customer@example.test',password:'test-password-only'});
      assert.equal(response.status,200);
      const login=await response.json() as {token:string;account:{id:string}};
      assert.equal(login.account.id,accountId);
      const headers={Authorization:`Bearer ${login.token}`,'Content-Type':'application/json'};
      await pool.query("UPDATE inventory SET on_hand=2 WHERE sku='TEST-A'");
      const quotation=await post('/v2/quotes',request,login.token);
      assert.equal(quotation.status,201);
      const data=await quotation.json() as {quote:{id:string}};
      const placed=await fetch(base+'/v2/orders',{method:'POST',headers:{...headers,'Idempotency-Key':'api-key-0001'},body:JSON.stringify({quoteId:data.quote.id})});
      assert.equal(placed.status,201);
      const created=await placed.json() as {order:{id:string}};
      await pool.query("UPDATE orders SET reservation_expires_at=now()-interval '1 second' WHERE id=$1",[created.order.id]);
      await assert.rejects(restarted.transition(payment,created.order.id,1,'paid'),code('RESERVATION_EXPIRED'));
      const expired=await Promise.all([restarted.expireReservations(),restarted.expireReservations()]);
      assert.equal(expired.reduce((sum,n)=>sum+n,0),1,'two workers release expired reservation once');
      assert.equal((await pool.query("SELECT reserved FROM inventory WHERE sku='TEST-A'")).rows[0].reserved,0);
      assert.equal((await fetch(base+'/v2/orders',{headers})).status,200);
      assert.equal((await fetch(base+`/v2/orders/${created.order.id}/status`,{method:'PATCH',headers,body:JSON.stringify({version:1,status:'paid'})})).status,403);
      assert.equal((await post('/v2/auth/logout',{},login.token)).status,200);
      assert.equal((await fetch(base+'/v2/orders',{headers})).status,401);
    } finally {await new Promise<void>((resolve,reject)=>api.close(e=>e?reject(e):resolve()));}
  } finally {
    await pool.end();
    await root.query(`DROP SCHEMA "${schema}" CASCADE`);
    await root.end();
  }
});
