import fs from 'node:fs';
import { env, launch, mailTo, shot, sql, step, watch, STATE_FILE } from './lib.mjs';

const EMAIL = process.env.CUSTOMER_EMAIL ?? `cliente.${Date.now()}@example.com`;
const browser = await launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, locale: 'it-IT' });
const page = await ctx.newPage();
watch(page, 'shop');

step('Browse: home → catalogue → product');
await page.goto(env.SHOP_URL, { waitUntil: 'networkidle' });
// Desktop masthead: department links; the breadcrumb leads back to the whole catalogue.
await page.getByRole('link', { name: 'Tutti i prodotti' }).first().click();
await page.getByText('Padella antiaderente 28 cm').last().waitFor();
await page.getByRole('link', { name: 'Cucina', exact: true }).first().click();
await page.getByRole('heading', { name: 'Cucina' }).waitFor();
await page.getByRole('link', { name: 'Catalogo', exact: true }).first().click();
await page.getByRole('heading', { name: 'Tutti i prodotti' }).waitFor();
if (!/\/catalog/.test(page.url())) throw new Error(`breadcrumb left the catalogue: ${page.url()}`);
await page.getByText('Padella antiaderente 28 cm').last().waitFor();
await shot(page, 'catalogo');
await page.getByText('Padella antiaderente 28 cm').last().click();
await page.waitForURL(/\/product\//);
await page.waitForLoadState('networkidle');
await shot(page, 'prodotto');

step('Cart: add product, open cart');
await page.getByText('Aggiungi al carrello').last().click();
await page.waitForTimeout(500);
await page.goto(`${env.SHOP_URL}/catalog`, { waitUntil: 'networkidle' });
// Quick-add a second product from the catalogue card "+" button.
const card = page.getByText('Carta cucina 6 rotoli').last();
await card.click();
await page.waitForURL(/\/product\//);
await page.getByText('Aggiungi al carrello').last().click();
await page.waitForTimeout(500);
await page.goto(`${env.SHOP_URL}/cart`, { waitUntil: 'networkidle' });
await page.getByText('Accedi e continua').last().waitFor();
await page.waitForLoadState('networkidle');
await page.getByLabel('Modifica consegna').last().click();
await page.getByRole('radio', { name: /Consegna a domicilio/ }).last().click();
await page.getByText('Consegna a domicilio').first().waitFor();
await page.waitForLoadState('networkidle');
await shot(page, 'carrello');
console.log('  cart:', (await page.innerText('body')).replace(/\s+/g, ' ').match(/Carrello.{0,400}/)?.[0]);

step('Checkout requires sign-in → email OTP');
// Signed out, the cart button goes straight to sign-in and returns to checkout afterwards.
await page.getByText('Accedi e continua').last().click();
await page.waitForURL(/\/auth\/sign-in/);
const since = Date.now() - 1000;
// The sign-in page opens on email + password; a new customer uses the email code.
await page.getByText('Accedi con un codice').last().click();
await page.getByLabel('Email').last().fill(EMAIL);
await page.getByText('Invia codice').last().click();
await page.getByLabel('Codice a 6 cifre').last().waitFor();
const mail = await mailTo(EMAIL, since);
const code = (mail.Text ?? mail.HTML).match(/\b(\d{6})\b/)?.[1];
console.log(`  email "${mail.Subject}" → code ${code}`);
await shot(page, 'codice-otp');
await page.getByLabel('Codice a 6 cifre').last().fill(code);
await page.getByText('Accedi', { exact: true }).last().click();
await page.waitForURL(/\/checkout$/);
await page.getByText('Indirizzo di consegna').last().waitFor();
await page.waitForLoadState('networkidle');

step('Checkout form: home delivery');
await page.getByLabel('Nome e cognome').last().fill('Mario Rossi');
await page.getByLabel('Via e numero civico').last().fill('Via di Prova 1');
await page.getByLabel('Città').last().fill('Lucca');
await page.getByLabel('Prov.').last().fill('LU');
await page.getByLabel('CAP').last().fill('55100');
await page.getByLabel('Telefono').last().fill('+39 333 1234567');
await page.getByRole('checkbox').filter({ hasText: 'Condizioni di vendita' }).last().click({ position: { x: 10, y: 10 } });
await page.waitForLoadState('networkidle');
await shot(page, 'checkout');
const payBtn = page.getByText(/^Paga €/).filter({ visible: true }).last();
const payLabel = await payBtn.innerText();
console.log(`  button: ${payLabel}`);

step('Pay on (mock) Stripe Checkout with 4242 test card');
await payBtn.click();
await page.waitForURL(/localhost:12111\/c\/pay\//, { timeout: 20000 });
await shot(page, 'stripe-checkout');
console.log(`  stripe amount: ${await page.getByTestId('amount').innerText()}`);
await page.getByRole('button', { name: /Paga/ }).click();
await page.waitForURL(/\/checkout\/return/, { timeout: 20000 });
await page.getByText('Grazie, ordine ricevuto').last().waitFor({ timeout: 30000 });
await shot(page, 'grazie');
const thanks = (await page.innerText('body')).replace(/\s+/g, ' ').match(/Grazie, ordine ricevuto.{0,160}/)?.[0];
console.log(`  ${thanks}`);
const orderNumber = thanks.match(/Ordine (\S+)/)?.[1];
const row = await sql(`select id,status,payment_status,total_cents,stripe_payment_intent_id from orders where order_number='${orderNumber}'`);
console.log(`  db: ${row}`);

step('Customer order detail');
await page.getByText("Segui l'ordine").last().click();
await page.waitForURL(/\/order\//);
await page.waitForLoadState('networkidle');
await shot(page, 'ordine-cliente');
step('Verified buyer reviews a purchased product');
const padella = await sql(`select id from products where sku = 'padella-28'`);
await page.goto(`${env.SHOP_URL}/product/${padella}`, { waitUntil: 'networkidle' });
await page.getByText('Scrivi una recensione').last().click();
await page.getByRole('radio', { name: '5 stelle' }).last().click();
await page.getByLabel('Commento').last().fill('Scalda in modo uniforme, manico comodo.');
await page.getByText('Pubblica recensione').last().click();
await page.getByText('Grazie! La tua recensione è pubblicata.').last().waitFor();
await shot(page, 'recensione');
console.log(`  db: ${await sql(`select rating_count, rating_avg from products where sku = 'padella-28'`)}`);

step('Password: set it in Profilo, then sign in with email + password');
const PASS = 'Cliente-Local-Pass-1';
const signOut = async () => {
  await page.goto(`${env.SHOP_URL}/profile`, { waitUntil: 'networkidle' });
  await page.getByText("Esci dall'account").last().click();
  await page.getByText('Accedi o registrati').last().waitFor();
};
await page.goto(`${env.SHOP_URL}/account/password`, { waitUntil: 'networkidle' });
await page.getByLabel('Nuova password').last().fill(PASS);
await page.getByLabel('Ripeti la password').last().fill(PASS);
await page.getByText('Salva password').last().click();
await page.getByText('Password salvata').last().waitFor();
await signOut();
await page.goto(`${env.SHOP_URL}/auth/sign-in`, { waitUntil: 'networkidle' });
await page.getByLabel('Email').last().fill(EMAIL);
await page.getByLabel('Password', { exact: true }).last().fill('password-sbagliata');
await page.getByText('Accedi', { exact: true }).last().click();
await page.getByText(/Email o password non corretti/).last().waitFor();
await page.getByLabel('Password', { exact: true }).last().fill(PASS);
await page.getByText('Accedi', { exact: true }).last().click();
await page.waitForURL(/\/profile/);
await page.getByText(EMAIL).last().waitFor();
await shot(page, 'accesso-password');
console.log('  signed in with email + password');

step('Register with email + password (email confirmation code)');
await signOut();
const NEW = `nuovo.${Date.now()}@example.com`;
const sinceNew = Date.now() - 1000;
await page.goto(`${env.SHOP_URL}/auth/sign-in`, { waitUntil: 'networkidle' });
await page.getByText('Crea un account').last().click();
await page.getByLabel('Email').last().fill(NEW);
await page.getByLabel('Password', { exact: true }).last().fill('corta');
await page.getByText('Crea account').last().click();
await page.getByText(/almeno 8 caratteri/).last().waitFor();
await page.getByLabel('Password', { exact: true }).last().fill(PASS);
await page.getByText('Crea account').last().click();
await page.getByText('Conferma la tua email').last().waitFor();
const confirm = await mailTo(NEW, sinceNew);
const newCode = (confirm.Text ?? confirm.HTML).match(/\b(\d{6})\b/)?.[1];
await page.getByLabel('Codice a 6 cifre').last().fill(newCode);
await page.getByText('Conferma', { exact: true }).last().click();
await page.waitForURL(/\/profile/);
await page.getByText(NEW).last().waitFor();
console.log(`  new account ${NEW} confirmed with code ${newCode}`);

step('Phone layout (design D): brand header, tabs, Volantino');
const phone = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: 'it-IT', isMobile: true, hasTouch: true });
const pp = await phone.newPage();
await pp.goto(env.SHOP_URL, { waitUntil: 'networkidle' });
await pp.getByText('Le nostre migliori offerte', { exact: false }).last().waitFor();
await pp.getByText('Volantino', { exact: true }).first().waitFor();
await shot(pp, 'telefono-home');
await pp.getByRole('tab', { name: /Carrello/ }).last().click();
await pp.getByText('Carrello', { exact: true }).last().waitFor();
await pp.goto(`${env.SHOP_URL}/volantino`, { waitUntil: 'networkidle' });
await pp.getByText(/Nessun volantino al momento|Valido dal|Scarica il PDF|Apri il volantino/).first().waitFor();
await shot(pp, 'telefono-volantino');
await phone.close();
console.log('  phone home, cart tab and Volantino render');

const prev = fs.existsSync(STATE_FILE) ? JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')) : { orders: [] };
fs.writeFileSync(STATE_FILE, JSON.stringify({ orders: [...(prev.orders ?? []), orderNumber] }));
await browser.close();
